In [1]:
# nympy.array Example 4

In [3]:
import numpy as np
a = np.array([1,2,3],dtype = complex)
print (a)

[1.+0.j 2.+0.j 3.+0.j]


In [4]:
#numpy, data type

In [5]:
import numpy as np

In [7]:
dt = np.dtype([('age',np.int8)])
print(dt)

[('age', 'i1')]


In [8]:
# numpy.dtype -exam 6

In [9]:
dt = np.dtype([('age',np.int8)])
a = np.array([(10,),(20,),(30,)], dtype = dt)
print (a['age'])

[10 20 30]


In [10]:
#numpy.shape examp 1

In [11]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
print (a.shape)

(2, 3)


In [12]:
#numpy.shape examp 2

In [13]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
a.shape =(3,2)
print(a)

[[1 2]
 [3 4]
 [5 6]]


In [14]:
#numpy.shape examp 3

In [18]:
import numpy as np
a = np.array([[1,2,3],[4,5,6]])
b= a.reshape(3,2)
print(b)

[[1 2]
 [3 4]
 [5 6]]


In [19]:
# numpy ndim examp 2

In [20]:
import numpy as np
a = np.arange(24)
a.ndim

#now reshape it
b = a.reshape(2,4,3)
print(b)

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [21]:
#numpy flags  example

In [22]:
import numpy as np
x = np.array([1,2,3,4,5])
print (x.flags)

  C_CONTIGUOUS : True
  F_CONTIGUOUS : True
  OWNDATA : True
  WRITEABLE : True
  ALIGNED : True
  WRITEBACKIFCOPY : False
  UPDATEIFCOPY : False


In [23]:
#numpy zeros examp 1

In [24]:
import numpy as np
x = np.zeros(7)
print(x)

[0. 0. 0. 0. 0. 0. 0.]


In [25]:
x = np.zeros((7),dtype = np.int)
print(x)

[0 0 0 0 0 0 0]


In [26]:
#numpy ones 

In [27]:
import numpy as np

In [30]:
x = np.ones([8,8],dtype = float)
print(x)

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]
