In [2]:
import numpy as np
a = np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
import numpy as np
a = np.array([[1,2],[3,4]])
print(a)

[[1 2]
 [3 4]]


In [3]:
import numpy as np
a = np.array([1,2,3,4,5],ndmin = 2)
print(a)

[[1 2 3 4 5]]


In [2]:
import numpy as np
a = np.array([1,2,3],dtype=complex)
print(a)

[1.+0.j 2.+0.j 3.+0.j]
