In [11]:
import numpy as np
s = 'Hello World'
a = np.frombuffer(s)
print(a)

TypeError: a bytes-like object is required, not 'str'

In [8]:
import numpy as np
x= np.arange(10,20,2, dtype= float)
print(x)

[10. 12. 14. 16. 18.]


In [13]:
import numpy as np
x = np. linspace(10,20,4 ,endpoint =False)
print(x)

[10.  12.5 15.  17.5]


In [16]:
import numpy as np
x = np. linspace(1,2,5 ,retstep=True ,endpoint=False)
print(x)

(array([1. , 1.2, 1.4, 1.6, 1.8]), 0.2)


In [19]:
import numpy as np
a = np.logspace(1,2.0,num=10)
print(a)

[ 10.          12.91549665  16.68100537  21.5443469   27.82559402
  35.93813664  46.41588834  59.94842503  77.42636827 100.        ]


In [23]:
import numpy as np
a = np.arange(20)
s = slice(2,18,2)
print(a[s])

[ 2  4  6  8 10 12 14 16]


In [26]:
import numpy as np
a = np.arange(20)
s = a[2:7:2]
print(s)

[2 4 6]


In [27]:
import numpy as np
a = np.arange(10)
print (a[2:])

[2 3 4 5 6 7 8 9]


In [28]:
a = np.arange(10)
print(a[2:5])

[2 3 4]


In [29]:
a= np.array([1,2,3],[3,4,5],[4,5,6])
print(a)
print(a[1:])

ValueError: only 2 non-keyword arguments accepted

In [31]:
a = np.array([[1,2,3],[2,4,5],[3,4,5]])
print(a)
print(a[...,1])
print(a[1,...])
print(a[...,1:])

[[1 2 3]
 [2 4 5]
 [3 4 5]]
[2 4 4]
[2 4 5]
[[2 3]
 [4 5]
 [4 5]]


In [36]:
a = np.array([[3,7],[9,1]])
print(a)
print('\n')
print(np.sort(a))
print('\n')
print(np.sort(a,axis=0))
print('\n')

dt= np.dtype([('name','S10'),('age',int)])
a= np.array([("raju",21),("anil",25),("ravi",17), ("amar",27)],dtype=dt)

print(a)
print('\n')
print(np.sort(a,order='name'))

[[3 7]
 [9 1]]


[[3 7]
 [1 9]]


[[3 1]
 [9 7]]


[(b'raju', 21) (b'anil', 25) (b'ravi', 17) (b'amar', 27)]


[(b'amar', 27) (b'anil', 25) (b'raju', 21) (b'ravi', 17)]


In [ ]:
()